encryptionsalt: v1:zlYb4fWsQsM=:v1:1aWq+/j3fXMeu5bz:gZSrZRbKRS4YUc7pQrrheZqp1im/eQ==
config:
  aws:region: us-west-2
  cognitoRegion: us-west-2
  cognitoUserPoolId: us-west-2_cZd2FyC4g
  cognitoClientId: 1lg8ab88foqkg9upe0v3t7krs6
