encryptionsalt: v1:aIKDKVeMFFk=:v1:ACjtrlp0QBw6TZ03:RQ5fD5Kng5toZwbfM7XFYYinCCrm0Q==
config:
  aws:region: us-west-2
  cognitoRegion: us-west-2
  cognitoUserPoolId: us-west-2_E17RlloBP
  cognitoClientId: 4chj22ktu0op51bs8obgrn46p0