name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: pip install tox
      - run: tox
  deploy:
    needs: [build]
    runs-on: [ubuntu-latest]
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: us-west-2
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - run: |
          python3.8 -m venv deploy-env
          source deploy-env/bin/activate
          pip install -r requirements.txt
          pip install zappa
      - name: create dev aws resources
        run: aws sqs create-queue --queue-name DEV-service-template-example2 --attributes "VisibilityTimeout=180"
      - name: deploy dev
        run: |
          source deploy-env/bin/activate
          zappa update dev
      - name: create production aws resources
        if: github.event_name == 'push'
        run: aws sqs create-queue --queue-name PROD-service-template-example2 --attributes "VisibilityTimeout=180"
      - name: deploy production
        if: github.event_name == 'push'
        run: |
          source deploy-env/bin/activate
          zappa deploy production
